// Generated by CoffeeScript 1.7.1
var bookly;

bookly = bookly || {};

bookly.bookApp = angular.module("bookApp", []);

bookly.BooksController = function($scope) {
  $scope.books = books;
  $scope.options = ['author', 'title', 'price'];
  $scope.cartItems = [];
  $scope.count = 0;
  $scope.addItemsToCart = function(index) {
    var addAnotherItem;
    addAnotherItem = $scope.books[index];
    if ($scope.cartItems.indexOf(addAnotherItem) >= 0) {
      $scope.cartItems[$scope.cartItems.indexOf(addAnotherItem)].quantity += 1;
    } else {
      addAnotherItem.quantity = 1;
      $scope.cartItems.push(addAnotherItem);
    }
    return $scope.count++;
  };
  $scope.removeItemFromCart = function(index) {
    $scope.cartItems.splice(index);
    $scope.count = 0;
  };
  $scope.clearCart = function() {
    $scope.cartItems = [];
    $scope.count = 0;
  };
  $scope.total = function() {
    var total;
    total = 0;
    _.each($scope.cartItems, function(item) {
      total += item.quantity * item.price;
    });
    return total;
  };
};
