// Generated by CoffeeScript 1.7.1
var bookly;

bookly = bookly || {};

bookly.bookApp = angular.module("bookApp", []);

bookly.BooksController = function($scope) {
  $scope.books = books;
  $scope.itmes = [];
  $scope.total = 0;
  $scope.totalItems = 0;
  $scope.add = function() {
    $scope.totalItems += 1;
    this.book.count = this.book.count || 0;
    if (this.book.count === 0) {
      $scope.items.push(this.book);
    }
    this.book.count += 1;
    $scope.total += this.book.price;
    return this;
  };
  return $scope.clear = function() {
    var item, items, _i, _len, _ref;
    _ref = $scope.items;
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      items = _ref[_i];
      item = 0;
    }
    item.count = 0;
    $scope.items = [];
    $scope.total = 0;
    return $scope.totalItems = 0;
  };
};
