// Generated by CoffeeScript 1.7.1
var bookly;

bookly = bookly || {};

bookly.bookApp = angular.module("bookApp", []);

bookly.BooksController = function($scope) {
  $scope.books = books;
  $scope.selects = ['author', 'title', 'price'];
  $scope.select = 'title';
  $scope.cartBooks = [];
  $scope.orderTotal = 0;
  $scope.cartItemCount = 0;
  $scope.addToCart = function(book) {
    if ($scope.cartBooks.indexOf(book) >= 0) {
      $scope.cartBooks[$scope.cartBooks.indexOf(book)].quantity += 1;
      $scope.orderTotal += book.price;
      $scope.cartItemCount += 1;
    } else {
      book.quantity += 1;
      $scope.cartBooks.push(book);
      $scope.orderTotal += book.price;
      $scope.cartItemCount += 1;
    }
  };
  return $scope.emptyCart = function() {
    $scope.cartBooks = [];
    $scope.cartItemCount = 0;
    $scope.orderTotal = 0;
  };
};

s;
