// Generated by CoffeeScript 1.7.1
var bookly;

bookly = bookly || {};

bookly.bookApp = angular.module('bookApp', []);

bookly.BooksController = function($scope) {
  $scope.books = books;
  $scope.checkout = [];
  $scope.itemCount = 0;
  $scope.add = function(index) {
    var addedBook;
    addedBook = $scope.books[index];
    if ($scope.checkout.indexOf(addedBook) >= 0) {
      $scope.checkout[$scope.checkout.indexOf(addedBook)].quantity += 1;
    } else {
      addedBook.quantity = 1;
      $scope.checkout.push(addedBook);
    }
    return $scope.itemCount++;
  };
  $scope.total = function() {
    var item, moolah, _i, _len, _ref;
    moolah = 0;
    _ref = $scope.checkout;
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      item = _ref[_i];
      moolah += item.price * item.quantity;
    }
    return moolah;
  };
  return $scope.empty = function() {
    $scope.checkout = [];
    return $scope.itemCount = 0;
  };
};
