// Generated by CoffeeScript 1.7.1
var bookly;

bookly = bookly || {};

bookly.bookApp = angular.module("bookApp", []);

bookly.BooksController = function($scope) {
  $scope.books = books;
  $scope.cartBooks = [];
  $scope.total = 0;
  $scope.count = 0;
  $scope.selects = ['author', 'title', 'price'];
  $scope.select = "title";
  $scope.addCart = function(book) {
    if (this.cartBooks.indexOf(book) >= 0) {
      book.quantity += 1;
      this.total += book.price;
      $scope.count += 1;
    } else {
      book.quantity = 1;
      this.cartBooks.push(book);
      this.total += book.price;
      $scope.count += 1;
    }
  };
  $scope.emptyCart = function() {
    this.cartBooks = [];
    $scope.count = 0;
    this.total = 0;
  };
};
