// Generated by CoffeeScript 1.7.1
var bookly;

bookly = bookly || {};

bookly.bookApp = angular.module("bookApp", []);

bookly.CoffeeController = function($scope) {
  $scope.books = books;
  $scope.cart = [];
  $scope.itemCount = 0;
  $scope.addToCart = function(index) {
    var addedBook;
    addedBook = $scope.books[index];
    $scope.cart.push(addedBook);
    $scope.itemCount++;
    return void 0;
  };
  $scope.total = function() {
    var total;
    total = 0.0;
    angular.forEach($scope.cart, function(item, key) {
      return total += item.price;
    });
    return total;
  };
  $scope.emptyCart = function(index) {
    $scope.cart = [];
    return $scope.itemCount = 0;
  };
  return void 0;
};
