// Generated by CoffeeScript 1.7.1
var bookly;

bookly = bookly || {};

bookly.bookApp = angular.module("bookApp", []);

bookly.NewController = function($scope) {
  $scope.books = books;
  $scope.orderProperty = "title";
  $scope.cart = [];
  $scope.addToCart = function(aBook) {
    if ($scope.cart.indexOf(aBook) === -1) {
      return $scope.cart.push(aBook);
    }
  };
  $scope.clearCart = function() {
    return $scope.cart = [];
  };
  return $scope.cartTotal = function() {
    var total;
    total = 0.0;
    angular.forEach($scope.cart, function(item, key) {
      return total += item.price;
    });
    return total;
  };
};
